### ISSUE TITLE
aol-feature click event doesn't work.

### ISSUE THREAD

**Issue by j-nord** [quentin-ol/ngx-openlayers#105]
The click-event in aol-feature doesn't work:

<aol-feature #feature *ngFor="let e of tabelleErgebnis; let i = index" (click)="clickKarte(e)" [id]="i">

The onClick-event in aol-map also doesn't work.

Version: "ngx-openlayers": "0.6.10"
Angular Version: 4.4.3

    <aol-map #Karte width="100%" height="100%" (onClick)="clickMap($event)">
        
        <aol-interaction-default></aol-interaction-default>
        <aol-view [zoom]="11">
            <aol-coordinate [x]="mitteLaengengrad" [y]="mitteBreitengrad" [srid]="'EPSG:4326'"></aol-coordinate>
        </aol-view>
        <aol-layer-tile>
            <aol-source-osm></aol-source-osm>
        </aol-layer-tile>
        <aol-layer-vector [opacity]="opacity">
            <aol-source-vector>
                <aol-feature #feature *ngFor="let e of tabelleErgebnis; let i = index" (click)="clickKarte(e)" [id]="i">
                    <aol-geometry-point>
                        <aol-coordinate [x]="e.laengengrad" [y]="e.breitengrad" [srid]="'EPSG:4326'"></aol-coordinate>
                    </aol-geometry-point>
                    <aol-style>
                        <aol-style-icon src="images/haus.png" style="cursor:pointer;" [scale]="1">
                        </aol-style-icon>
                    </aol-style>
                </aol-feature>
            </aol-source-vector>
        </aol-layer-vector>
    </aol-map>

**Comment by quentin-ol** [comment]
We'll need more information to help you with this. Could you provide a minimal example that reproduces the bug? Right now, I can't test based on your code as I don't have access to your source.

**Comment by seidlt** [comment]
The onClick events also do not work for me. However, the problem occurs only on some Android Smartphones. So I tried it with the example code of this repository and added the `onClick` to the `aol-map`:

    <aol-map` [width]="'100%'" [height]="'100%'" (onClick)="handleEvent($event)">

But the handleEvent `method` is only called 1 out of 100 tries... 
On iOS and on a Desktop is works.

**Comment by quentin-ol** [comment]
My understanding is that the issue doesn't lie in this library but in OpenLayers itself. Since we're a few minor versions behind OpenLayers (see #106), it might be a good idea to test with Openlayers 4.4.x  and see if it fixes the issue: https://github.com/openlayers/openlayers/issues/6824 reports the same kind of error and 4.2 is reported to fix it.

**Comment by quentin-ol** [comment]
anyone willing to help on this?

**Comment by seidlt** [comment]
I tried it with openlayers 4.4.1 and it worked!
So you are right, this it not a issue with this library.

**Comment by quentin-ol** [comment]
Should be solved with the latest package: 0.7.11. Can you confirm?

**Comment by seidlt** [comment]
Yes I can confirm. Its works how it should - Thank you.

**Comment by dydFreeman** [comment]
Still having some issues in retrieving a click event on a feature, which have a geometry-linestring in it. As you can see in this example (https://stackblitz.com/edit/testngxopenlayers) i managed to get a map click event, but not a feature one.
Am i doing something wrong?

**Comment by dydFreeman** [comment]
Made few more tests, i can now subscribe to the map click event and then check if it comes from a feature:

```
    this.mapComponent.onClick.subscribe((event) => {
      console.log(event.coordinate);
      console.log(event.pixel);
      var features = this.mapComponent.instance.getFeaturesAtPixel(event.pixel);
      if (features) {
        this.featureClickData = 'Feature clicked!';
        console.log('Feature!', features);
      } else {
        this.featureClickData = 'No click on feature yet, sorry!';
      }
    })
```

But still, no way of intercepting the click event directly from the template.
LINK: https://stackblitz.com/edit/testngxopenlayers

**Comment by BabakVandad** [comment]
I don't know if you are still looking for a solution, but:
If you give the `<aol-feature/>` element an `id` property, then you may read that `id` in your .ts file like this:

```
    var features = this.mapComponent.instance.getFeaturesAtPixel(event.pixel);
    (features[0] as Feature).getId()
```

That's not exactly what you wanted buy I guess that will do the trick :)

**Comment by LuisAngelMoralesRomo** [comment]
I made this directive to get the `(onClick)` event on `<aol-feature>`, hope it helps.

```ts
import { Directive, Output, EventEmitter } from '@angular/core';
import { MapComponent, FeatureComponent } from 'ngx-openlayers';

@Directive({ selector: 'aol-feature[onClick]' })
export class FeatureClickDirective {

  @Output() onClick: EventEmitter<ol.MapBrowserEvent>;

  constructor(
    private map: MapComponent,
    private feature: FeatureComponent
  ) {
    this.onClick = new EventEmitter<ol.MapBrowserEvent>();
    this.map.onClick.subscribe((event: ol.MapBrowserEvent) => {
      const clickedFeatures = this.map.instance.getFeaturesAtPixel(event.pixel);
      for (const clickedFeature of clickedFeatures || []) {
        if (clickedFeature === this.feature.instance) {
          this.onClick.emit(event);
        }
      }
    });
  }
}
```
