### ISSUE TITLE
Missing marker.png file in Demo App

### ISSUE THREAD

**Issue by sughodke** [quentin-ol/ngx-openlayers#119]
The demo app references marker.png in the assets folder, however its not checked in.  I think someone just forgot to do a git add.

https://github.com/quentin-ol/ngx-openlayers/blob/master/example/src/app/app.component.html#L27

**Comment by quentin-ol** [comment]
Hey @sughodke, thanks for catching this. Fixed in 6d4ece9380335b86841317ddce0e1787091f4651

**Comment by MiftahulxHuda** [comment]
@sughodke I attempt to add an icon to a marker but still don't work. Give me a sample code to add the icon to the marker.
